Implementation of release-automation exception process
eclipse-tractusx/sig-release pull request #558
Opened 2024-03-07 13:27 UTC by tomaszbarwicki

To be added

2024-03-15 11:04 UTC, tomaszbarwicki commented
UT TestShouldPassIfExceptionDataIsAtURL fails because the file doesn't exists yet, it's part of the PR items.

2024-03-21 08:16 UTC, almadigabor commented
Hey @tomaszbarwicki! Great work here. One remark that the code block below is repeated many times in different quality checks. Is there a way to refactor it to be a reusable function in all files?

```go
	config, err := exception.GetData()
	if err != nil {
		log.Println("Can't process exceptions.")
	} else {
		repoInfo := repo.GetRepoBaseInfo(a.baseDir)
		if config.IsExceptioned(a.Name(), "https://github.com/eclipse-tractusx/"+repoInfo.Reponame) {
			return &tractusx.QualityResult{Passed: true}
		}
	}
```

2024-03-27 14:15 UTC, tomaszbarwicki commented
> Hey @tomaszbarwicki! Great work here. One remark that the code block below is repeated many times in different quality checks. Is there a way to refactor it to be a reusable function in all files?
> 
> ```go
> config, err := exception.GetData()
> if err != nil {
> 	log.Println("Can't process exceptions.")
> } else {
> 	repoInfo := repo.GetRepoBaseInfo(a.baseDir)
> 	if config.IsExceptioned(a.Name(), "https://github.com/eclipse-tractusx/"+repoInfo.Reponame) {
> 		return &tractusx.QualityResult{Passed: true}
> 	}
> }
> ```

Thanks for feedback @almadigabor, I made the changes and moved the code outside the checks into command line runner and dashboard, hope that looks better now :). Please review.

2024-04-02 08:36 UTC, almadigabor approved these changes, later dismissed

2024-04-04 12:53 UTC, SebastianBezold requested changes
Some things I would like to see changed. 
Additionally, I think doing a string compare on the TRG name to find out, if there is an exception for it, could become quite error prone. When refactoring, or renaming, we need to make sure, it is done in both places. An alternative option could be to introduce IDs, since they would potentially be treated as "do not change". 

But fine for now with comparing the name

2024-04-08 08:18 UTC, tomaszbarwicki commented on release-automation/EXCEPTIONS.md
> +   - Review the structure of the [exceptions.yaml](https://github.com/eclipse-tractusx/sig-release/blob/main/release-automation/internal/exception/exceptions.yaml) file to understand how exceptions a
corrected: https://github.com/eclipse-tractusx/sig-release/pull/558/commits/74bfe3050a73eb45bd095a36b2fdccb698dad138

2024-04-08 08:20 UTC, tomaszbarwicki commented on release-automation/EXCEPTIONS.md
> +6. **Assigning Reviewers:**
shortened: https://github.com/eclipse-tractusx/sig-release/pull/558/commits/74bfe3050a73eb45bd095a36b2fdccb698dad138

2024-04-08 08:34 UTC, tomaszbarwicki commented on release-automation/internal/dashboard/tractusx.go
> +			repoInfo := repo.GetRepoBaseInfo(check.BaseDir())
@SebastianBezold: Indeed that would work for dashboard build run, however for CLI run I don't think I have other option to get the repo directory hence the getter added to interface.

2024-04-08 12:32 UTC, tomaszbarwicki commented on release-automation/internal/exception/exception.go
> +func GetData() (*Config, error) {
Made it ExceptionsMap return type:
https://github.com/eclipse-tractusx/sig-release/blob/5336a436e14d726b360280c7c0f030536d1b139f/release-automation/internal/exception/exception.go#L42

2024-04-08 12:34 UTC, tomaszbarwicki commented on release-automation/internal/exception/exception.go
> +func (c *Config) IsExceptioned(trg string, repository string) bool {
Reduced the loops by the map usage:
https://github.com/eclipse-tractusx/sig-release/blob/5336a436e14d726b360280c7c0f030536d1b139f/release-automation/internal/exception/exception.go#L81-L86

2024-04-11 11:22 UTC, SebastianBezold commented on release-automation/internal/dashboard/tractusx.go
> +			repoInfo := repo.GetRepoBaseInfo(check.BaseDir())
Hmm ok, I guess we can live with that, even though I think we could find a better solutions in the future

2024-04-11 12:17 UTC, SebastianBezold approved these changes
👍

2024-04-11 12:18 UTC, merged