feat: add issue template request promotion
eclipse-tractusx/sig-release pull request #6
Opened 2023-06-19 09:10 UTC by LuisRickert

---
name: Add request KIT Promotion Issue Template
title: feat add issue templates to request promotion
---

## Description

With this PR we introduce the issue templates to request a promotion for an existing KIT. Raising such an issue will trigger the review process.

2023-06-28 13:30 UTC, FaGru3n commented on .github/ISSUE_TEMPLATE/issue-request-promotion-incubating.yaml
> +
i think just a single blank line will be ok 😉

2023-06-28 13:31 UTC, FaGru3n commented on .github/ISSUE_TEMPLATE/issue-request-promotion-graduated.yaml
> +  - octocat
I would leave this out if it is not clear who will be responsible @octocat seems for me to generic

2023-07-05 12:48 UTC, FaGru3n commented on .github/ISSUE_TEMPLATE/issue-request-promotion-graduated.yaml
> +  - octocat
hi @LuisRickert also your could reference it and make it as resolved 😉 
[chore: remove octocat as asignee, remove unneccessary information](https://github.com/eclipse-tractusx/sig-project-managment/pull/6/commits/e2ad74d20343f14dabadc8ce903cc8aaa0b6f805)

2023-07-17 07:47 UTC, carslen requested changes

2023-07-17 07:47 UTC, carslen commented on .github/ISSUE_TEMPLATE/issue-request-promotion-graduated.yaml
> +        - label: Standarts
This is not art but Standard ;)

2023-09-19 12:55 UTC, FaGru3n commented
Hi @LuisRickert because this `sig-release` repo is getting more usage of planning and overviewing the release path and processes do you think a new repo would be nice, like "sig-kit" in my opnion it makes it easier to keep on track with the release process and planning things ... and also for the requests against it...?

beside the fact more and more KIT´s will be developed... so after the time of requests against

2023-09-21 07:45 UTC, LuisRickert commented
> Hi @LuisRickert because this `sig-release` repo is getting more in usage of planning and overviewing the release path and processes do you think a new repo would be nice, like "sig-kit" in my opinion it makes it easier to keep on track with the release process and planning things ... and also for the requests against it...?
> 
> beside the fact more and more KIT´s will be developed... i would prefer a special repo for a special interest group 😉

Well i guess then a dedicated Repository is the right was

2023-09-27 08:39 UTC, RolaH1t commented
@FaGru3n after several discussions (e.g. with @danielmiehle) I can confirm, that we will "park" the idea of an additional/separate RePo for KITs for the moment. Please work with @kelaja to process all release-relevant issues for KITs also within the SIG Release RePo. We will review the idea towards the and of PI10, once initial learnings can be applied.

2023-09-27 08:39 UTC, RolaH1t commented
@LuisRickert please dismiss this PullRequest. @danielmiehle will also confirm here, that the initial idea of a template to promote a KIT shall not be used for the time being. Thx, Roland

2023-09-28 13:30 UTC, FaGru3n commented
I will close the PR according to the message from @RolaH1t

2023-09-28 13:30 UTC, closed without merging